apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: exam-robindemeyer
  labels:
    # Replace this by your own name
    createdBy: "Robin-DeMeyer"
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: robindemeyer/big_data_and_ai-24_may_api
          imagePullPolicy: Always
          name: api-demo
          ports:
            - containerPort: 80
          resources: {}
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
          - name: NAME
            value: "Robin De Meyer"
          - name: DATE
            value: "2024-05-08"

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30000