apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: exam-robindemeyer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        image: robindemeyer/big_data_and_ai-24_may_frontend:versie1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: API_PORT
          value: "80"
        - name: API_HOST
          value: api.exam-robindemeyer.svc.cluster.local
        - name: NAME
          value: "Robin De Meyer"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: app
  ports:
    ports:
    - port: 80
      targetPort: 8000
      nodePort: 30000
  nodeSelector:
    kubernetes.io/robindemeyer: k3d-k3s-default-agent-2



