services:
  api:
    image: robindemeyer/big_data_and_ai-24_may_api:versie1
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - 8001:80
  frontend:
    image: robindemeyer/big_data_and_ai-24_may_frontend:versie1
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8000:80
    environment:
      API_PORT: 80
      API_HOST: api
      NAME: "Nathan Segers"
