version: '3.9'

services:
  web:
    build: ./pointsApp
    networks:
      - web
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: ghcr.io/eslih/postgres:16.1-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - database
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - .env
networks:
  database:
  web:
volumes:
  postgres: