version: '3.9'

services:
  web:
    build: ./pointsApp
    networks:
      - web
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://POSTGRES_USER:POSTGRES_PASSWORD@database:5432/POSTGRES_DB
  db:
    image: ghcr.io/eslih/postgres:16.1-alpine
    environment:
      POSTGRES_DB: POSTGRES_DB
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
    networks:
      - database

networks:
  database:
  web:
